name: xarray-tutorial
channels:
  - conda-forge
dependencies:
  - python=3.10
  # for building website:
  - jupyter-book=0.13
  - pre-commit
  # for user interface
  - dask-labextension
  - jupyterlab>=3
  - jupyter-resource-usage
  # for default notebook kernel:
  - cartopy
  - cf_xarray
  - dask
  - distributed
  - gcsfs
  - geoviews
  - gsw
  - hvplot
  - matplotlib-base
  - netcdf4
  - pint-xarray
  - pydap
  - python-graphviz
  - pooch
  - rioxarray
  - scipy
  - xarray
  - zarr
