name: Pull Request Build

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    paths-ignore:
      - ".devcontainer/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        if: github.event.action != 'closed'
        uses: actions/checkout@v4

      - name: Setup JupyterBook Cache
        if: github.event.action != 'closed'
        uses: actions/cache@v4
        with:
          path: _build
          # NOTE: change key to "jupyterbook-DATE" to force rebuilding cache
          key: jupyterbook-20250221

      - uses: prefix-dev/setup-pixi@v0.8.2
        with:
          manifest-path: pyproject.toml
          cache: true
          activate-environment: true

      - name: Build JupyterBook
        if: github.event.action != 'closed'
        run: |
          jupyter-book build ./ --warningiserror --keep-going

      - name: Dump Build Logs
        if: github.event.action != 'closed'
        run: |
          if (test -a _build/html/reports/*log); then cat _build/html/reports/*log ; fi

      - name: Upload artifact
        if: github.event.action != 'closed'
        uses: actions/upload-artifact@v4
        with:
          name: html
          path: _build/html
